import Head from "next/head";
import Hero from "@/components/Hero";
import { Inter } from "next/font/google";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Market Maven - Your E-Commerce Expert for Unbeatable Deals & Seamless
          Shopping
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div>
        <Hero />
      </div>
    </>
  );
}
